version: "3"
services:
  https:
    image: steveltn/https-portal:1
    ports:
      - "8080:80"
      - "2443:443"
    environment:
      STAGE: local
      DOMAINS: "localhost -> http://node:3000"
      WEBSOCKET: "true"
    networks:
      - all
  node:
    image: node:16
    networks:
      - all
    volumes:
      - ".:/workspace"
    working_dir: "/workspace"
    command: "npm run dev"

networks:
  all:
    driver: bridge
